### ISSUE TITLE
ECX Follow-up. Urgent Attention Required

### ISSUE THREAD

**Issue by KeneNwogu** [adedamola-toye/Unilag-PathFinder#3]
Hello, you submitted this repository as your favourite project. It's great work, but you didn't send your contact details on the form. I would love to talk about the project. If you are still up for it, can you send your email as a comment on this issue?

Regards,
Kenechukwu.
Development Lead, ECX 5.0.

**Comment by adedamola-toye** [comment]
toye.adedamola@gmail.com

**Comment by KeneNwogu** [comment]
Thank you for the swift response. Kind regards.
